version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_project_web
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: my_project_db
      DB_USERNAME: my_project_user
      DB_PASSWORD: my_project_password
    depends_on:
      - db
    networks:
      - my_project_network
  db:
    image: postgres:latest
    container_name: my_project_db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: my_project_db
      POSTGRES_USER: my_project_user
      POSTGRES_PASSWORD: my_project_password
    ports:
      - "5432:5432"
    networks:
      - my_project_network
networks:
  my_project_network:
volumes:
  pgdata:
